copyviewer:
	cp ../../docubricksViewer/WebContent/viewerbundle.js        js/
	cp ../../docubricksViewer/WebContent/lightbox*.css          css/
	cp ../../docubricksViewer/WebContent/lightbox*.js           js/
	cp ../../docubricksViewer/WebContent/docubricksViewer.css   css/

