copyviewer:
	cp ../../docubricksViewer/WebContent/viewerbundle.js        js/
	cp ../../docubricksViewer/WebContent/lightbox*.css          css/
	cp ../../docubricksViewer/WebContent/lightbox*.js           js/
	cp ../../docubricksViewer/WebContent/docubricksViewer.css   css/

	cp ../../docubricksViewer/WebContent/node_modules/react/dist/react.js \
	   ../../docubricksViewer/WebContent/node_modules/react-dom/dist/react-dom.js \
		js/
